///////////////////////////////////////////////////////////
//  SSMainViewModel.cs
//  Implementation of the Class SSMainViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Windows;
using SS.ShareScreen.Core.MVVM;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.Main;
using SS.ShareScreen.Interfaces.System;

namespace SS.ShareScreen.ViewModels
{
    [Export(typeof(ISSMainViewModel))]
    public class SSMainViewModel : SSUIBaseViewModel<ISSMainView>, ISSMainViewModel
    {
        private List<ISSScreenShotViewModel> _screenShotList;

        public SSMainViewModel()
        {
        }

        ~SSMainViewModel()
        {
        }

        ///
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
        }

        ///
        /// <param name="view"></param>
        public override void HideDialog(ISSView view)
        {
        }

        ///
        /// <param name="parentModel"></param>
        public override void Initialize(ISSUIViewModel parentModel)
        {
            MenuViewModel?.InitializeMenu(ExecuteMenuCommand,CanExecuteManuCommand);
            //MouseSystem?.StartSystem();
            //KeyboardSystem?.StartSystem();
            //PluginSystem?.StartSystem();
            //ScreenShotSystem?.StartSystem();
        }

        public void ShowMainWindow()
        {
            (View as Window).Show();
        }

        [Import]
        private ISSKeyboardSystem KeyboardSystem
        {
            get; set;
        }

        [Import]
        public ISSMainMenuViewModel MenuViewModel
        {
            get; set;
        }

        [Import]
        private ISSMouseSystem MouseSystem
        {
            get; set;
        }

        [Import]
        private ISSPluginSystem PluginSystem
        {
            get; set;
        }

        [Import]
        private ISSScreenshotSystem ScreenShotSystem
        {
            get; set;
        }

        [Import]
        public ISSMainStatusBarViewModel StatusBarViewModel
        {
            get; set;
        }


        private void ExecuteMenuCommand(object arg)
        {
            
        }



        private bool CanExecuteManuCommand(object arg)
        {
            return true;
        }

    }//end SSMainViewModel
}//end namespace ViewModels