///////////////////////////////////////////////////////////
//  SSMainMenuViewModel.cs
//  Implementation of the Class SSMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using SS.ShareScreen.Core.MVVM;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.Main;

namespace SS.ShareScreen.ViewModels
{
    [Export(typeof(ISSMainMenuViewModel))]
    public class SSMainMenuViewModel : SSUIBaseViewModel<ISSMainMenuView>, ISSMainMenuViewModel
    {
        public SSMainMenuViewModel()
        {
        }

        ~SSMainMenuViewModel()
        {
        }

        ///
        /// <param name="disposing"></param>
        protected void Dispose(bool disposing)
        {
        }

        public IEnumerable<ISSMenuItemViewModel> File
        {
            get
            {
                return File;
            }
        }

        public IEnumerable<ISSMenuItemViewModel> Help
        {
            get
            {
                return Help;
            }
        }

        ///
        /// <param name="excuteAction"></param>
        /// <param name="canExecuteAction"></param>
        public void InitializeMenu(Action<object> excuteAction, Func<object, bool> canExecuteAction)
        {
        }
    }//end SSMainMenuViewModel
}//end namespace ViewModels