///////////////////////////////////////////////////////////
//  SSMainMenuViewModel.cs
//  Implementation of the Class SSMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using SS.ShareScreen.Core.MVVM;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.Main;
using SS.ShareScreen.ViewModels.Menu.File;

namespace SS.ShareScreen.ViewModels
{
    [Export(typeof(ISSMainMenuViewModel))]
    public class SSMainMenuViewModel : SSUIBaseViewModel<ISSMainMenuView>, ISSMainMenuViewModel
    {
        public SSMainMenuViewModel()
        {
        }

        ~SSMainMenuViewModel()
        {
        }

        ///
        /// <param name="disposing"></param>
        protected void Dispose(bool disposing)
        {
        }

        public IEnumerable<ISSMenuItemViewModel> File { get; private set; }

        public IEnumerable<ISSMenuItemViewModel> Help { get; private set; }

        ///
        /// <param name="executeAction"></param>
        /// <param name="canExecuteAction"></param>
        public void InitializeMenu(Action<object> executeAction, Func<object, bool> canExecuteAction)
        {
            File = new List<ISSMenuItemViewModel>()
            {
                new SSScreeShotMenuItem(executeAction,canExecuteAction)
                {
                    SubItems = new List<ISSMenuItemViewModel>()
                    {
                        new SSMakeAllScreenMenuItem(executeAction,canExecuteAction),
                        new SSMakeRegionScreenMenuItem(executeAction,canExecuteAction),
                        new SSActiveWindowMenuItem(executeAction,canExecuteAction)
                    }
                },
                new SSCloseMenuItem(executeAction,canExecuteAction)
            };
            
        }
    }//end SSMainMenuViewModel
}//end namespace ViewModels