///////////////////////////////////////////////////////////
//  SSMainViewModel.cs
//  Implementation of the Class SSMainViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using SS.ShareScreen.Core.MVVM;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.Main;
using SS.ShareScreen.Interfaces.System;

namespace SS.ShareScreen.ViewModels
{
    public class SSMainViewModel : SSBaseViewModel, ISSMainViewModel
    {
        private Interfaces.System.ISSKeyboardSystem _keyboardSystem;
        private Interfaces.Main.ISSMainMenuViewModel _menuViewModel;
        private Interfaces.System.ISSMouseSystem _mouseSystem;
        private Interfaces.System.ISSPluginSystem _pluginSystem;
        private List<ISSScreenShotViewModel> _screenShotList;
        private Interfaces.System.ISSScreenshotSystem _screenShotSystem;
        private Interfaces.Main.ISSMainStatusBarViewModel _statusBarViewModel;
        public Interfaces.Core.ISSMenuViewModel m_ISSMenuViewModel;

        public SSMainViewModel()
        {
        }

        ~SSMainViewModel()
        {
        }

        ///
        /// <param name="disposing"></param>
        protected void Dispose(bool disposing)
        {
        }

        ///
        /// <param name="view"></param>
        public int HideDialog(ISSView view)
        {
            return 0;
        }

        ///
        /// <param name="parentModel"></param>
        public void Initialize(ISSUIViewModel parentModel)
        {
        }

        private ISSKeyboardSystem KeyboardSystem
        {
            get
            {
                return _keyboardSystem;
            }
            set
            {
                _keyboardSystem = value;
            }
        }

        public ISSMainMenuViewModel MenuViewModel
        {
            get
            {
                return _menuViewModel;
            }
        }

        private ISSMouseSystem MouseSystem
        {
            get
            {
                return _mouseSystem;
            }
            set
            {
                _mouseSystem = value;
            }
        }

        private ISSPluginSystem PluginSystem
        {
            get
            {
                return _pluginSystem;
            }
            set
            {
                _pluginSystem = value;
            }
        }

        private ISSScreenshotSystem ScreenShotSystem
        {
            get
            {
                return _screenShotSystem;
            }
            set
            {
                _screenShotSystem = value;
            }
        }

        public ISSMainStatusBarViewModel StatusBarViewModel
        {
            get
            {
                return _statusBarViewModel;
            }
            set
            {
                _statusBarViewModel = value;
            }
        }
    }//end SSMainViewModel
}//end namespace ViewModels