///////////////////////////////////////////////////////////
//  SSScreenShotViewModel.cs
//  Implementation of the Class SSScreenShotViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.ComponentModel.Composition;
using SS.ShareScreen.Core.MVVM;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.Main;

namespace SS.ShareScreen.ViewModels
{
    [Export(typeof(ISSScreenShotViewModel))]
    public class SSScreenShotViewModel : SSUIBaseViewModel<ISSScreenShotView>, ISSScreenShotViewModel
    {
        public SSScreenShotViewModel()
        {
        }

        ~SSScreenShotViewModel()
        {
        }

        ///
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
        }
        
    }//end SSScreenShotViewModel
}//end namespace ViewModels