///////////////////////////////////////////////////////////
//  SSSubscriptionToken.cs
//  Implementation of the Class SSSubscriptionToken
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using ShareScreen.Core.Interfaces.InteractionManager;

namespace ShareScreen.Core.Core.InteractionManager
{
    public class SSSubscriptionToken : ISSSubscribeToken, IEquatable<ISSSubscribeToken>
    {
        public SSSubscriptionToken()
        {
            Id = Guid.NewGuid();
        }

        ~SSSubscriptionToken()
        {
        }

        public Guid Id
        {
            get; private set;
        }

        public bool Equals(ISSSubscribeToken other)
        {
            return (other == null) ? false 
               : Equals(other,other.Id);
        }

        public override bool Equals(object obj)
        {
            return ReferenceEquals(this,obj);
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }//end SSSubscriptionToken
}//end namespace InteractionManager