///////////////////////////////////////////////////////////
//  SSLogger.cs
//  Implementation of the Class SSLogger
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.ComponentModel.Composition;
using NLog;
using ShareScreen.Core.Interfaces.Core;

namespace ShareScreen.Core.Logger
{
    [Export(typeof(ISSLogger))]
    public class SSLogger : ISSLogger
    {

        private static NLog.Logger Logger => LogManager.GetCurrentClassLogger();

        [ImportingConstructor]
        public SSLogger()
        {
        }

        ~SSLogger()
        {
        }


        public void Error(string message)
        {
#if DEBUG
            System.Diagnostics.Debug.WriteLine(message);
#endif

            Logger?.Error(message);
        }

        public void Debug(string message)
        {
#if DEBUG
            System.Diagnostics.Debug.WriteLine(message);
#endif
            Logger?.Debug(message);
        }

        public void Info(string message)
        {
#if DEBUG
            System.Diagnostics.Debug.WriteLine(message);
#endif

            Logger?.Info(message);
        }

        public void Warning(string message)
        {
#if DEBUG
            System.Diagnostics.Debug.WriteLine(message);
#endif

            Logger?.Warn(message);
        }
    }//end SSLogger
}//end namespace Logger