///////////////////////////////////////////////////////////
//  SSLogger.cs
//  Implementation of the Class SSLogger
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Logger
{
    public class SSLogger
    {
        public SSLogger()
        {
        }

        ~SSLogger()
        {
        }
    }//end SSLogger
}//end namespace Logger