///////////////////////////////////////////////////////////
//  SSPayload.cs
//  Implementation of the Class SSPayload
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.ShareScreen.Interfaces.Core;

namespace SS.ShareScreen.Core.Payload
{
    public class SSPayload<T> : ISSPayload
    {
        private T value;

        public SSPayload()
        {
        }
        public T Value
        {
            get
            {
                return this.value;
            }
            set
            {
                this.value = value;
            }
        }
    }//end SSPayload
}//end namespace Payload