///////////////////////////////////////////////////////////
//  SSPayload.cs
//  Implementation of the Class SSPayload
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Core.Payload
{
    public class SSPayload<T>
    {
        private T value;

        public SSPayload()
        {
        }

        ~SSPayload()
        {
        }

        public T Value
        {
            get
            {
                return Value;
            }
            set
            {
                Value = value;
            }
        }
    }//end SSPayload
}//end namespace Payload