///////////////////////////////////////////////////////////
//  SSUIBaseViewModel.cs
//  Implementation of the Class SSUIBaseViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.ShareScreen.Interfaces.Core;

namespace SS.ShareScreen.Core.MVVM
{
    public class SSUIBaseViewModel<T> : SSBaseViewModel
        where T : ISSView
    {
        public T View;

        public SSUIBaseViewModel()
        {
        }

        ~SSUIBaseViewModel()
        {
        }
    }//end SSUIBaseViewModel
}//end namespace MVVM