///////////////////////////////////////////////////////////
//  ISSMainView.cs
//  Implementation of the Interface ISSMainView
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.ShareScreen.Interfaces.Core;

namespace SS.ShareScreen.Interfaces.Main
{
    public interface ISSMainView : ISSView
    {
    }//end ISSMainView
}//end namespace Main