///////////////////////////////////////////////////////////
//  ISSMainMenuViewModel.cs
//  Implementation of the Interface ISSMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using SS.ShareScreen.Interfaces.Core;

namespace SS.ShareScreen.Interfaces.Main
{
    public interface ISSMainMenuViewModel : ISSMenuViewModel
    {
        IEnumerable<ISSMenuItemViewModel> File
        {
            get;
        }

        IEnumerable<ISSMenuItemViewModel> Help
        {
            get;
        }
    }//end ISSMainMenuViewModel
}//end namespace Main