///////////////////////////////////////////////////////////
//  ISSScreenShotViewModel.cs
//  Implementation of the Interface ISSScreenShotViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.ShareScreen.Interfaces.Core;

namespace SS.ShareScreen.Interfaces.Main
{
    public interface ISSScreenShotViewModel : ISSUIViewModel
    {
    }//end ISSScreenShotViewModel
}//end namespace Main