///////////////////////////////////////////////////////////
//  ISSCommandProvider.cs
//  Implementation of the Interface ISSCommandProvider
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;

namespace SS.ShareScreen.Interfaces.InteractionManager
{
    public interface ISSCommandProvider<TPayload> : ISSCommonCommandProvider
    {
        ///
        /// <param name="args"></param>
        void Publish(TPayload args);

        ///
        /// <param name="action"></param>
        void Subscribe(Action<TPayload> action);

        ///
        /// <param name="token"></param>
        void Unsubscribe(ISSSubscribeToken token);
    }//end ISSCommandProvider
}//end namespace InteractionManager