///////////////////////////////////////////////////////////
//  ISSCommonCommandProvider.cs
//  Implementation of the Interface ISSCommonCommandProvider
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Interfaces.InteractionManager
{
    public interface ISSCommonCommandProvider
    {
    }//end ISSCommonCommandProvider
}//end namespace InteractionManager