///////////////////////////////////////////////////////////
//  ISSSubscribeToken.cs
//  Implementation of the Interface ISSSubscribeToken
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;

namespace SS.ShareScreen.Interfaces.InteractionManager
{
    public interface ISSSubscribeToken
    {
        Guid Id
        {
            get;
        }
    }//end ISSSubscribeToken
}//end namespace InteractionManager