///////////////////////////////////////////////////////////
//  SSBasePlugin.cs
//  Implementation of the Class SSBasePlugin
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:54
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Drawing;
using SS.PluginCore.Interfaces;

namespace SS.PluginCore.Core
{
    public class SSBasePlugin : ISSSharePlugin
    {
        public SSBasePlugin()
        {
        }

        ~SSBasePlugin()
        {
        }

        public ISSSharePluginAuthorization Authorize
        {
            get; protected set;
        }

        public ISSSharePluginBrowser Browser { get; protected set; }

        public Bitmap Icon { get; protected set; }

        public Guid Id { get; protected set; }

        public string Name { get; protected set; }

        public ISSSharePluginSharing Sharing { get; protected set; }

        public string UIName { get; protected set; }
    }//end SSBasePlugin
}//end namespace Core