///////////////////////////////////////////////////////////
//  SSBaseSharePluginSharing.cs
//  Implementation of the Class SSBaseSharePluginSharing
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:54
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.PluginCore.Interfaces;

namespace SS.PluginCore.Core
{
    public class SSBaseSharePluginSharing : ISSSharePluginSharing
    {
        public SSBaseSharePluginSharing()
        {
        }

        ~SSBaseSharePluginSharing()
        {
        }

        ///
        /// <param name="fileId"></param>
        /// <param name="credentionals"></param>
        protected virtual ISSSharingUrlResult DoGetSharingUrl(string fileId, params object[] credentionals)
        {
            return null;
        }

        protected virtual ISSUploadResult DoUploadFile()
        {
            return null;
        }

        ///
        /// <param name="fileId"></param>
        /// <param name="credentionals"></param>
        public ISSSharingResult<ISSSharingUrlResult> GetSharingUrl(string fileId, params object[] credentionals)
        {
            return null;
        }

        public ISSSharingResult<ISSUploadResult> UploadFile()
        {
            return null;
        }
    }//end SSBaseSharePluginSharing
}//end namespace Core