///////////////////////////////////////////////////////////
//  ISSSharingResult.cs
//  Implementation of the Interface ISSSharingResult
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:54
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.PluginCore.Interfaces
{
    public interface ISSSharingResult<T>
    {
        T Result { get; }

        bool Succeed { get; }
    }//end 
}//end namespace Interfaces