///////////////////////////////////////////////////////////
//  ISSSharePluginSharing.cs
//  Implementation of the Interface ISSSharePluginSharing
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:53
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.PluginCore.Interfaces
{
    public interface ISSSharePluginSharing
    {
        ///
        /// <param name="fileId"></param>
        /// <param name="credentionals"></param>
        ISSSharingResult<ISSSharingUrlResult> GetSharingUrl(string fileId, params object[] credentionals);

        ISSSharingResult<ISSUploadResult> UploadFile();
    }//end ISSSharePluginSharing
}//end namespace Interfaces