///////////////////////////////////////////////////////////
//  ISSSharePluginAuthorization.cs
//  Implementation of the Interface ISSSharePluginAuthorization
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:53
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.PluginCore.Interfaces
{
    public interface ISSSharePluginAuthorization
    {
        bool Authorize();

        bool IsAuthorized();
    }//end ISSSharePluginAuthorization
}//end namespace Interfaces