///////////////////////////////////////////////////////////
//  ISSSharePluginBrowser.cs
//  Implementation of the Interface ISSSharePluginBrowser
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:53
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.PluginCore.Interfaces
{
    public interface ISSSharePluginBrowser
    {
    }//end ISSSharePluginBrowser
}//end namespace Interfaces