///////////////////////////////////////////////////////////
//  ISSUploadResult.cs
//  Implementation of the Interface ISSUploadResult
//  Generated by Enterprise Architect
//  Created on:      16-Nov-2015 00:19:54
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.PluginCore.Interfaces
{
    public interface ISSUploadResult
    {
    }//end ISSUploadResult
}//end namespace Interfaces