///////////////////////////////////////////////////////////
//  SSKeyboardPayload.cs
//  Implementation of the Class SSKeyboardPayload
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using SS.ShareScreen.Core.Payload;
using SS.ShareScreen.Enums;

namespace SS.ShareScreen.Payloads
{
    public class SSKeyboardPayload : SSPayload<eScreenshotType>
    {
        public SSKeyboardPayload()
        {
        }

        ~SSKeyboardPayload()
        {
        }

    }//end SSKeyboardPayload
}//end namespace Payloads