///////////////////////////////////////////////////////////
//  SSCommand.cs
//  Implementation of the Class SSCommand
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;

namespace SS.ShareScreen.Core.Command
{
    public class SSCommand
    {
        private Func<bool> _canExecute;
        private Action<object> _execute;

        public SSCommand()
        {
        }

        ~SSCommand()
        {
        }

        ///
        /// <param name="action"></param>
        public SSCommand(Action<object> action)
        {
        }

        ///
        /// <param name="execute"></param>
        /// <param name="canExecute"></param>
        public SSCommand(Action<object> execute, Func<bool> canExecute)
        {
        }
    }//end SSCommand
}//end namespace Command