///////////////////////////////////////////////////////////
//  SSBaseCommandProvider.cs
//  Implementation of the Class SSBaseCommandProvider
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSBaseCommandProvider : ISSCommonCommandProvider
    {
        private IDictionary<ISSSubscribeToken, ISSSubscription> subscribers;

        public SSBaseCommandProvider()
        {
        }

        ~SSBaseCommandProvider()
        {
        }

        ///
        /// <param name="args"></param>
        protected void InternalPublish(object args)
        {
        }

        ///
        /// <param name="subscription"></param>
        protected void InternalSubscribe(ISSSubscription subscription)
        {
        }

        ///
        /// <param name="token"></param>
        protected void InternalUnsubscribe(ISSSubscribeToken token)
        {
        }
    }//end SSBaseCommandProvider
}//end namespace InteractionManager