///////////////////////////////////////////////////////////
//  SSCommandProvider.cs
//  Implementation of the Class SSCommandProvider
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using SS.ShareScreen.Core.Payload;
using SS.ShareScreen.Interfaces.Core;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSCommandProvider<TPayload> : SSBaseCommandProvider, ISSCommandProvider<TPayload> where TPayload : ISSPayload
    {
        public SSCommandProvider()
        {
        }

        ~SSCommandProvider()
        {
        }

        ///
        /// <param name="args"></param>
        public void Publish(TPayload args)
        {
            InternalPublish(args);
        }

        ///
        /// <param name="action"></param>
        public ISSSubscribeToken Subscribe(Action<TPayload> action)
        {
            var subscription = new SSCommandSubscription<TPayload>(new SSReferenceDelegate(action));
            return InternalSubscribe(subscription);
        }

        ///
        /// <param name="token"></param>
        public void Unsubscribe(ISSSubscribeToken token)
        {
            InternalUnsubscribe(token);
        }
    }//end SSCommandProvider
}//end namespace InteractionManager