///////////////////////////////////////////////////////////
//  SSCommandProvider.cs
//  Implementation of the Class SSCommandProvider
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSCommandProvider<TPayload> : SSBaseCommandProvider, ISSCommandProvider<TPayload>
    {
        public SSCommandProvider()
        {
        }

        ~SSCommandProvider()
        {
        }

        ///
        /// <param name="args"></param>
        public void Publish(TPayload args)
        {
        }

        ///
        /// <param name="action"></param>
        public void Subscribe(Action<TPayload> action)
        {
        }

        ///
        /// <param name="token"></param>
        public void Unsubscribe(ISSSubscribeToken token)
        {
        }
    }//end SSCommandProvider
}//end namespace InteractionManager