///////////////////////////////////////////////////////////
//  SSCommandSubscription.cs
//  Implementation of the Class SSCommandSubscription
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSCommandSubscription<TPayload> : ISSSubscription
    {
        private Interfaces.InteractionManager.ISSReferenceDelegate _actionReference;
        private Action<TPayload> Action;
        public Interfaces.InteractionManager.ISSSubscribeToken Token;

        public SSCommandSubscription()
        {
        }

        ~SSCommandSubscription()
        {
        }

        ///
        /// <param name="arg"></param>
        public void Publish(object arg)
        {
        }
    }//end SSCommandSubscription
}//end namespace InteractionManager