///////////////////////////////////////////////////////////
//  SSInteractionManager.cs
//  Implementation of the Class SSInteractionManager
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSInteractionManager : ISSInteractionManager
    {
        private IDictionary<Type, ISSCommonCommandProvider> commandProviders;

        public SSInteractionManager()
        {
        }

        ~SSInteractionManager()
        {
        }

        public T GetCommand<T>()
        {
            throw new NotImplementedException();
        }
    }//end SSInteractionManager
}//end namespace InteractionManager