///////////////////////////////////////////////////////////
//  SSInteractionManager.cs
//  Implementation of the Class SSInteractionManager
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSInteractionManager : ISSInteractionManager
    {
        private IDictionary<Type, ISSCommonCommandProvider> commandProviders;

        public SSInteractionManager()
        {
            commandProviders = new Dictionary<Type, ISSCommonCommandProvider>();
        }

        ~SSInteractionManager()
        {
        }

        public T GetCommand<T>() where T: ISSCommonCommandProvider,new()
        {
            ISSCommonCommandProvider cmdProvider;
            if (!commandProviders.TryGetValue(typeof (T), out cmdProvider))
            {
                T provider = new T();
                commandProviders[typeof (T)] = provider;
                return provider;
            }
            return (T) cmdProvider;
        }
    }//end SSInteractionManager
}//end namespace InteractionManager