///////////////////////////////////////////////////////////
//  SSReferenceDelegate.cs
//  Implementation of the Class SSReferenceDelegate
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:26
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using SS.ShareScreen.Interfaces.InteractionManager;

namespace SS.ShareScreen.Core.InteractionManager
{
    public class SSReferenceDelegate : ISSReferenceDelegate
    {
        public SSReferenceDelegate()
        {
        }

        ~SSReferenceDelegate()
        {
        }

        public Delegate Target
        {
            get; set;
        }
    }//end SSReferenceDelegate
}//end namespace InteractionManager