///////////////////////////////////////////////////////////
//  eScreenshotType.cs
//  Implementation of the Enumeration eScreenshotType
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Enums
{
    public enum eScreenshotType : int
    {
        None,
        Screen,
        SelectedArea,
        SelectedWindow
    }//end eScreenshotType
}//end namespace Enums