///////////////////////////////////////////////////////////
//  eSSMenuCommand.cs
//  Implementation of the Enumeration eSSMenuCommand
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Enums
{
    public enum eSSMenuCommand : int
    {
        Close,
        ScreenShot,
        About,
        Preferences,
        MakeAllAcreen,
        MakeRegionScreen,
        MakeActiveWindow,

    }//end eSSMenuCommand
}//end namespace Enums