///////////////////////////////////////////////////////////
//  ISSMouseSystem.cs
//  Implementation of the Interface ISSMouseSystem
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Windows;

namespace SS.ShareScreen.Interfaces.System
{
    public interface ISSMouseSystem : ISSSystem
    {
        Tuple<Point, Point> GetSelectedArea();

        IntPtr GetSelectedWindow();

    }//end ISSMouseSystem
}//end namespace System