///////////////////////////////////////////////////////////
//  ISSScreenshotSystem.cs
//  Implementation of the Interface ISSScreenshotSystem
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Drawing;

namespace SS.ShareScreen.Interfaces.System
{
    public interface ISSScreenshotSystem : ISSSystem
    {
        Bitmap GetScreenshot();

        ///
        /// <param name="leftTop"></param>
        /// <param name="bottomRight"></param>
        Bitmap GetScreenshotOfSelectedArea(Point leftTop, Point bottomRight);

        ///
        /// <param name="handle"></param>
        Bitmap GetScreenshtOfSelectedWindow(IntPtr handle);
    }//end ISSScreenshotSystem
}//end namespace System