///////////////////////////////////////////////////////////
//  ISSSystem.cs
//  Implementation of the Interface ISSSystem
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Interfaces.System
{
    public interface ISSSystem
    {
        void StartSystem();

        void StopSystem();
    }//end ISSSystem
}//end namespace System