///////////////////////////////////////////////////////////
//  ISSMenuViewModel.cs
//  Implementation of the Interface ISSMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;

namespace SS.ShareScreen.Interfaces.Core
{
    public interface ISSMenuViewModel : ISSViewModel
    {
        ///
        /// <param name="excuteAction"></param>
        /// <param name="canExecuteAction"></param>
        void InitializeMenu(Action<object> excuteAction, Func<object, bool> canExecuteAction);

    }//end ISSMenuViewModel
}//end namespace Core