///////////////////////////////////////////////////////////
//  ISSUIViewModel.cs
//  Implementation of the Interface ISSUIViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace SS.ShareScreen.Interfaces.Core
{
    public interface ISSUIViewModel : ISSViewModel
    {
        ///
        /// <param name="view"></param>
        void HideDialog(ISSView view);

        ///
        /// <param name="parentModel"></param>
        void Initialize(ISSUIViewModel parentModel);

        ///
        /// <param name="view"></param>
        void ShowDialog(ISSView view);
        
        object View { get; }

    }//end ISSUIViewModel
}//end namespace Core