///////////////////////////////////////////////////////////
//  SSKeyboardPayload.cs
//  Implementation of the Class SSKeyboardPayload
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using ShareScreen.Core.Core.Payload;
using ShareScreen.Core.Enums;

namespace ShareScreen.Core.Payloads
{
    public class SSKeyboardPayload : SSPayload<eScreenshotType>
    {
        public SSKeyboardPayload()
        {
        }


    }//end SSKeyboardPayload
}//end namespace Payloads