///////////////////////////////////////////////////////////
//  ISSInteractionManager.cs
//  Implementation of the Interface ISSInteractionManager
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace ShareScreen.Core.Interfaces.InteractionManager
{
    public interface ISSInteractionManager
    {
        T GetCommand<T>() where T : ISSCommonCommandProvider,new();
    }//end ISSInteractionManager
}//end namespace InteractionManager