///////////////////////////////////////////////////////////
//  ISSReferenceDelegate.cs
//  Implementation of the Interface ISSReferenceDelegate
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;

namespace ShareScreen.Core.Interfaces.InteractionManager
{
    public interface ISSReferenceDelegate
    {
        Delegate Target
        {
            get;
        }
    }//end ISSReferenceDelegate
}//end namespace InteractionManager