///////////////////////////////////////////////////////////
//  ISSSubscription.cs
//  Implementation of the Interface ISSSubscription
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace ShareScreen.Core.Interfaces.InteractionManager
{
    public interface ISSSubscription
    {
        ///
        /// <param name="arg"></param>
        void Publish(object arg);

        ISSSubscribeToken Token { get; set; }
    }//end ISSSubscription
}//end namespace InteractionManager