///////////////////////////////////////////////////////////
//  ISSMainView.cs
//  Implementation of the Interface ISSMainView
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using ShareScreen.Core.Interfaces.Core;

namespace ShareScreen.Core.Interfaces.Main
{
    public interface ISSMainView : ISSView
    {
        void ShowDialog(ISSView view);

        void HideDialog(ISSView view);

        void MaximazeMainWindow();

        void MinimizeMainWindow();


        void NormalizeMainWindow();
    }//end ISSMainView
}//end namespace Main