///////////////////////////////////////////////////////////
//  ISSMainStatusBarViewModel.cs
//  Implementation of the Interface ISSMainStatusBarViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using ShareScreen.Core.Interfaces.Core;

namespace ShareScreen.Core.Interfaces.Main
{
    public interface ISSMainStatusBarViewModel : ISSUIViewModel
    {
    }//end ISSMainStatusBarViewModel
}//end namespace Main