///////////////////////////////////////////////////////////
//  ISSScreenShotViewModel.cs
//  Implementation of the Interface ISSScreenShotViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.Drawing;
using ShareScreen.Core.Interfaces.Core;

namespace ShareScreen.Core.Interfaces.Main
{
    public interface ISSScreenShotViewModel : ISSUIViewModel
    {
        void SetScreenShot(Bitmap screenShot);
        string Header { set; get; }

        void Save(string filename);

        void SaveAs();

        bool IsSaved { get; }

    }//end ISSScreenShotViewModel
}//end namespace Main