///////////////////////////////////////////////////////////
//  ISSKeyboardSystem.cs
//  Implementation of the Interface ISSKeyboardSystem
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace ShareScreen.Core.Interfaces.System
{
    public interface ISSKeyboardSystem : ISSSystem
    {
    }//end ISSKeyboardSystem
}//end namespace System