///////////////////////////////////////////////////////////
//  ISSMouseSystem.cs
//  Implementation of the Interface ISSMouseSystem
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.Windows;

namespace ShareScreen.Core.Interfaces.System
{
    public interface ISSMouseSystem : ISSSystem
    {
        Tuple<Point, Point> GetSelectedArea();

        IntPtr GetSelectedWindow();

        void RunSelectingWindow(IntPtr mainHwnd);
        void RunSelectingArea();
        void ResetCurrentAction();
    }//end ISSMouseSystem
}//end namespace System