///////////////////////////////////////////////////////////
//  eSSMenuCommand.cs
//  Implementation of the Enumeration eSSMenuCommand
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:24
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace ShareScreen.Core.Enums
{
    public enum eSSMenuCommand : int
    {
        None,
        Close,
        ScreenShot,
        About,
        Preferences,
        MakeAllScreen,
        MakeRegionScreen,
        MakeActiveWindow,
        Save,
        SaveAs

    }//end eSSMenuCommand
}//end namespace Enums