///////////////////////////////////////////////////////////
//  ISSView.cs
//  Implementation of the Interface ISSView
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

namespace ShareScreen.Core.Interfaces.Core
{
    public interface ISSView
    {
        ISSViewModel Model { get; set; }
    }//end ISSView
}//end namespace Core