///////////////////////////////////////////////////////////
//  ISSViewModel.cs
//  Implementation of the Interface ISSViewModel
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel;

namespace ShareScreen.Core.Interfaces.Core
{
    public interface ISSViewModel : IDisposable, INotifyPropertyChanged
    {
    }//end ISSViewModel
}//end namespace Core