///////////////////////////////////////////////////////////
//  SSBootstraper.cs
//  Implementation of the Class SSBootstraper
//  Generated by Enterprise Architect
//  Created on:      15-Nov-2015 22:31:25
//  Original author: Yariki
///////////////////////////////////////////////////////////

using System.ComponentModel.Composition.Hosting;
using SS.ShareScreen.Interfaces.Main;

namespace SS.ShareScreen
{

    public class SSBootstraper
    {
        private CompositionContainer _container;
        private ISSMainViewModel _mainViewModel;

        ~SSBootstraper()
        {
        }

        public SSBootstraper()
        {
        }

        public void Exit()
        {
        }

        private void Initialize()
        {
        }

        public void Run()
        {
        }
    }
    
//end SSBootstraper
}
